// ╔══════════════════════════════════════════════════════════╗
// ║  ESCAPE GAME — DONNÉES BLOC A (Séries 1-10)              ║
// ║  103 pathologies — oldyetsebastien.fr                    ║
// ╚══════════════════════════════════════════════════════════╝
const PENALTY_WRONG=10, PENALTY_HINT=20;
const DECODER=[{w:'b',r:'d'},{w:'d',r:'b'},{w:'m',r:'n'},{w:'n',r:'m'}];
const SYM=[
  {e:'🌸',n:'Endométriose',v:5},{e:'🥄',n:'Fatigue chronique',v:3},
  {e:'💉',n:'Diabète',v:2},{e:'🧠',n:'TDAH',v:6},
  {e:'🦋',n:'Lupus',v:7},{e:'💊',n:'Fibromyalgie',v:8},
  {e:'🌊',n:'Dépression',v:1},{e:'⚡',n:'Épilepsie',v:9}
];
// type: T=tableau A=anagramme C=confused S=symbols
// e=emoji dc=diffClass ans=answer tbl=table q=question eq=equation blur=blurred
const SERIES_A=[
{id:1,name:'Série 1',code:'3714',rooms:[
  {type:'T',e:'📋',diff:'Facile ★',dc:'diff1',title:'La Salle des Pathologies',sub:'Tableau de correspondance',ans:'3',
   tbl:[{n:0,p:'Fibromyalgie'},{n:1,p:'Dépression'},{n:2,p:'Dyslexie'},{n:3,p:'TDAH'},{n:4,p:'Endométriose'},{n:5,p:'Épilepsie'},{n:6,p:'TSA / Autisme'},{n:7,p:'SFC / Fatigue chronique'},{n:8,p:'Diabète type 1'},{n:9,p:'Dyspraxie'}],
   clues:["Je touche autant les enfants que les adultes. Je suis souvent diagnostiquée très tardivement — parfois seulement à l'âge adulte.","Mon acronyme de 4 lettres est souvent confondu avec de la paresse ou du manque de volonté. C'est faux : c'est neurologique.","En réunion ou en classe, je lutte pour rester concentrée. Mon cerveau recherche constamment de la stimulation."],
   hints:["Cette pathologie est neurologique. Son acronyme commence par T et finit par H.","TDAH = Trouble Déficitaire de l'Attention avec Hyperactivité.","TDAH est le numéro 3 dans le tableau."]},
  {type:'A',e:'🔤',diff:'Moyen ★★',dc:'diff2',title:'Le Laboratoire des Mots',sub:'Anagrammes de pathologies',ans:'7',
   words:[{s:'MISTEAU',sol:'AUTISME',note:'Trouble du spectre neurodéveloppemental'},{s:'EIXYLSED',sol:'DYSLEXIE',note:'Trouble des apprentissages'},{s:'MODERNISETOE',sol:'ENDOMETRIOSE',note:'Maladie gynécologique chronique'}],
   q:"Lequel désigne le trouble du spectre neurodéveloppemental ? Comptez ses lettres.",
   hints:["MISTEAU est l'anagramme du trouble du spectre.","MISTEAU → AUTISME. Comptez les lettres de ce mot.","A-U-T-I-S-M-E = 7 lettres."]},
  {type:'C',e:'🔀',diff:'Difficile ★★★',dc:'diff3',title:'Le Cerveau Embrouillé',sub:'b↔d et m↔n — simulation dyslexie',ans:'1',
   confused:"um sur bix em souffremt. la byslexie est um trouble b'appremtissage. le premier mombre écrit em lettres bams ce texte est votre chiffre.",
   decoded:"<span class='ch'>UN</span> sur dix en souffrent. la dyslexie est un trouble d'apprentissage. le premier nombre écrit en lettres dans ce texte est votre chiffre.",
   hints:["Règle : dans le texte confus, tout 'b' = 'd' et tout 'd' = 'b'. Pareil : 'm' = 'n' et 'n' = 'm'.","Le mot 'um' dans le texte confus se décode en 'un' (m→n).","Le premier nombre en lettres dans le texte décodé est UN = 1."]},
  {type:'S',e:'🔣',diff:'Très difficile ★★★★',dc:'diff4',title:'La Chambre des Codes',sub:'Symboles + équation',ans:'4',
   eq:'🌸 − 🥄 + 💉 = ?',blur:'Le résultat est pair, entre 3 et 5.',q:"Résolvez l'équation avec les valeurs du tableau.",
   hints:["Dans le tableau : 🌸=5, 🥄=3, 💉=2.","L'équation devient : 5 − 3 + 2 = ?","5 − 3 + 2 = 4."]}
]},
{id:2,name:'Série 2',code:'5826',rooms:[
  {type:'T',e:'📋',diff:'Facile ★',dc:'diff1',title:'La Salle des Pathologies',sub:'Tableau de correspondance',ans:'5',
   tbl:[{n:0,p:'Dépression'},{n:1,p:'TDAH'},{n:2,p:'TSA / Autisme'},{n:3,p:'Dyslexie'},{n:4,p:'Fibromyalgie'},{n:5,p:'Épilepsie'},{n:6,p:'Endométriose'},{n:7,p:'SFC / Fatigue chronique'},{n:8,p:'Diabète type 1'},{n:9,p:'Dyspraxie'}],
   clues:["Beaucoup croient que je provoque toujours des convulsions. Faux : certaines de mes crises ne sont qu'un regard fixe de quelques secondes — invisible.","Mon nom vient du grec 'être saisi'. Je touche 50 millions de personnes dans le monde. Je touche toutes les tranches d'âge.","Conduire, travailler en hauteur, rester seul dans un bain — des situations ordinaires, potentiellement dangereuses pour moi. Pourtant, rien de l'extérieur ne me signale."],
   hints:["Cette pathologie provoque des crises. Son nom vient du grec 'être saisi'.","Elle touche 50 millions de personnes dans le monde.","Épilepsie est le numéro 5 dans le tableau."]},
  {type:'A',e:'🔤',diff:'Moyen ★★',dc:'diff2',title:'Le Laboratoire des Mots',sub:'Anagrammes de pathologies',ans:'8',
   words:[{s:'EIXYLSED',sol:'DYSLEXIE',note:'Trouble des apprentissages'},{s:'SUPUL',sol:'LUPUS',note:'Maladie auto-immune'},{s:'EELPISIPE',sol:'EPILEPSIE',note:'Trouble neurologique par crises'}],
   q:"Lequel désigne le trouble des apprentissages lié à la lecture ? Comptez ses lettres.",
   hints:["EIXYLSED est l'anagramme du trouble des apprentissages.","EIXYLSED → DYSLEXIE. Comptez les lettres.","D-Y-S-L-E-X-I-E = 8 lettres."]},
  {type:'C',e:'🔀',diff:'Difficile ★★★',dc:'diff3',title:'Le Cerveau Embrouillé',sub:'b↔d et m↔n — simulation dyslexie',ans:'2',
   confused:"beux sur bix em souffremt. le hambicap imvisible m'est pas toujours compris. le premier mombre écrit em lettres bams ce texte est votre chiffre.",
   decoded:"<span class='ch'>DEUX</span> sur dix en souffrent. le handicap invisible n'est pas toujours compris. le premier nombre écrit en lettres dans ce texte est votre chiffre.",
   hints:["Règle : 'b'='d', 'd'='b', 'm'='n', 'n'='m' dans tout le texte confus.","Le mot 'beux' dans le texte confus se décode en 'deux' (b→d).","Le premier nombre en lettres est DEUX = 2."]},
  {type:'S',e:'🔣',diff:'Très difficile ★★★★',dc:'diff4',title:'La Chambre des Codes',sub:'Symboles + équation',ans:'6',
   eq:'🦋 + 🌊 − 💉 = ?',blur:'Le résultat est pair, entre 5 et 7.',q:"Résolvez l'équation avec les valeurs du tableau.",
   hints:["Dans le tableau : 🦋=7, 🌊=1, 💉=2.","L'équation devient : 7 + 1 − 2 = ?","7 + 1 − 2 = 6."]}
]},
{id:3,name:'Série 3',code:'9537',rooms:[
  {type:'T',e:'📋',diff:'Facile ★',dc:'diff1',title:'La Salle des Pathologies',sub:'Tableau de correspondance',ans:'9',
   tbl:[{n:0,p:'Fibromyalgie'},{n:1,p:'Dépression'},{n:2,p:'TDAH'},{n:3,p:'TSA / Autisme'},{n:4,p:'Endométriose'},{n:5,p:'Lupus'},{n:6,p:'SFC / Fatigue chronique'},{n:7,p:'Épilepsie'},{n:8,p:'Diabète type 1'},{n:9,p:'Dyspraxie'}],
   clues:["Je touche la coordination motrice. Nouer ses lacets, tenir un crayon — des gestes ordinaires qui deviennent un défi quotidien pour mon porteur.","On me confond souvent avec de la maladresse ou du manque d'effort. En réalité, mon cerveau peine à planifier les séquences de mouvements.","Je touche 5 à 7% de la population. Je suis souvent associée au TDAH ou à la dyslexie. Encore peu connue du grand public."],
   hints:["Cette pathologie touche la coordination motrice. Son nom commence par DYS-.","Elle est souvent surnommée 'maladresse d'origine cérébrale'. Touche 5-7% de la population.","Dyspraxie est le numéro 9 dans le tableau."]},
  {type:'A',e:'🔤',diff:'Moyen ★★',dc:'diff2',title:'Le Laboratoire des Mots',sub:'Anagrammes de pathologies',ans:'5',
   words:[{s:'SUPUL',sol:'LUPUS',note:'Maladie auto-immune chronique'},{s:'XIDAYREPS',sol:'DYSPRAXIE',note:'Trouble de la coordination motrice'},{s:'HETSAM',sol:'ASTHME',note:'Maladie respiratoire chronique'}],
   q:"Lequel désigne la maladie auto-immune chronique ? Comptez ses lettres.",
   hints:["SUPUL est l'anagramme de la maladie auto-immune.","SUPUL → LUPUS. Comptez les lettres.","L-U-P-U-S = 5 lettres."]},
  {type:'C',e:'🔀',diff:'Difficile ★★★',dc:'diff3',title:'Le Cerveau Embrouillé',sub:'b↔d et m↔n — simulation dyslexie',ans:'3',
   confused:"trois sur bix em souffremt. les pathologies imvisibles m'omt pas be fromt. le premier mombre écrit em lettres bams ce texte est votre chiffre.",
   decoded:"<span class='ch'>TROIS</span> sur dix en souffrent. les pathologies invisibles n'ont pas de front. le premier nombre écrit en lettres dans ce texte est votre chiffre.",
   hints:["Règle : 'b'='d', 'm'='n'. Cherchez le premier nombre en lettres dans le texte décodé.","TROIS ne contient ni b, ni d, ni m, ni n — il reste INCHANGÉ dans le texte confus. C'est le piège !","Le premier nombre en lettres est TROIS = 3."]},
  {type:'S',e:'🔣',diff:'Très difficile ★★★★',dc:'diff4',title:'La Chambre des Codes',sub:'Symboles + équation',ans:'7',
   eq:'🧠 + 🌊 = ?',blur:'Le résultat est impair, entre 6 et 8.',q:"Résolvez l'équation avec les valeurs du tableau.",
   hints:["Dans le tableau : 🧠=6, 🌊=1.","L'équation devient : 6 + 1 = ?","6 + 1 = 7."]}
]},
{id:4,name:'Série 4',code:'6354',rooms:[
  {type:'T',e:'📋',diff:'Facile ★',dc:'diff1',title:'La Salle des Pathologies',sub:'Tableau de correspondance',ans:'6',
   tbl:[{n:0,p:'Trouble bipolaire'},{n:1,p:'TOC'},{n:2,p:'Migraine chronique'},{n:3,p:'Narcolepsie'},{n:4,p:'Maladie de Crohn'},{n:5,p:'Hypersomnie'},{n:6,p:'Acouphènes'},{n:7,p:'TSPT'},{n:8,p:'Sclérose en plaques'},{n:9,p:'Hyperacousie'}],
   clues:["Je suis un bruit permanent que seul mon porteur entend. Sifflements, bourdonnements, tintements — sans aucune source extérieure réelle.","Je touche 15% des adultes en France. Je suis liée au stress, aux traumatismes sonores. Aucun scanner ne peut me révéler.","Le soir, dans le silence absolu, mon porteur m'entend encore plus fort. Le silence lui-même devient insupportable."],
   hints:["Cette pathologie est un bruit interne que seul le porteur perçoit.","En grec, 'akouein' = entendre. Elle touche 15% des adultes en France.","Acouphènes est le numéro 6 dans le tableau."]},
  {type:'A',e:'🔤',diff:'Moyen ★★',dc:'diff2',title:'Le Laboratoire des Mots',sub:'Anagrammes de pathologies',ans:'3',
   words:[{s:'COT',sol:'TOC',note:'Trouble obsessionnel compulsif'},{s:'SUPUL',sol:'LUPUS',note:'Maladie auto-immune'},{s:'HETSAM',sol:'ASTHME',note:'Maladie respiratoire'}],
   q:"Lequel désigne le trouble obsessionnel compulsif ? Comptez ses lettres.",
   hints:["COT est l'anagramme du trouble obsessionnel compulsif.","COT → TOC. Comptez les lettres.","T-O-C = 3 lettres."]},
  {type:'C',e:'🔀',diff:'Difficile ★★★',dc:'diff3',title:'Le Cerveau Embrouillé',sub:'b↔d et m↔n — simulation dyslexie',ans:'5',
   confused:"cimq pour cemt be la populatiom souffre b'acouphèmes sévères. le premier mombre em lettres bams ce texte est votre chiffre.",
   decoded:"<span class='ch'>CINQ</span> pour cent de la population souffre d'acouphènes sévères. le premier nombre en lettres dans ce texte est votre chiffre.",
   hints:["Règle : 'b'='d', 'm'='n'. Cherchez le premier nombre en lettres dans le texte décodé.","Le mot 'cimq' dans le texte confus se décode en 'cinq' (m→n).","Le premier nombre en lettres est CINQ = 5."]},
  {type:'S',e:'🔣',diff:'Très difficile ★★★★',dc:'diff4',title:'La Chambre des Codes',sub:'Symboles + équation',ans:'4',
   eq:'🌸 − 🌊 = ?',blur:'Le résultat est pair, entre 3 et 5.',q:"Résolvez l'équation avec les valeurs du tableau.",
   hints:["Dans le tableau : 🌸=5, 🌊=1.","L'équation devient : 5 − 1 = ?","5 − 1 = 4."]}
]},
{id:5,name:'Série 5',code:'7416',rooms:[
  {type:'T',e:'📋',diff:'Facile ★',dc:'diff1',title:'La Salle des Pathologies',sub:'Tableau de correspondance',ans:'7',
   tbl:[{n:0,p:'Dyscalculie'},{n:1,p:'Dysgraphie'},{n:2,p:'TOC'},{n:3,p:'Vitiligo'},{n:4,p:'TSPT'},{n:5,p:'Narcolepsie'},{n:6,p:'SOPK'},{n:7,p:'Dysorthographie'},{n:8,p:'Trouble bipolaire'},{n:9,p:'Sensibilité sensorielle'}],
   clues:["Je touche la façon d'écrire les mots. Les règles d'orthographe résistent malgré tous les efforts et l'intelligence.","On peut me lire correctement mais mal m'écrire. Je suis distincte de la dyslexie, même si souvent associée à elle.","En dictée ou en production écrite, les erreurs persistent. Ce n'est pas de la négligence — c'est neurologique."],
   hints:["Cette pathologie touche l'orthographe. Son nom commence par DYS-.","On peut bien lire mais mal orthographier. Elle est distincte de la dyslexie.","Dysorthographie est le numéro 7 dans le tableau."]},
  {type:'A',e:'🔤',diff:'Moyen ★★',dc:'diff2',title:'Le Laboratoire des Mots',sub:'Anagrammes de pathologies',ans:'4',
   words:[{s:'OKPS',sol:'SOPK',note:'Syndrome des ovaires polykystiques'},{s:'SUPUL',sol:'LUPUS',note:'Maladie auto-immune'},{s:'HETSAM',sol:'ASTHME',note:'Maladie respiratoire'}],
   q:"Lequel désigne le syndrome gynécologique lié aux ovaires ? Comptez ses lettres.",
   hints:["OKPS est l'anagramme du syndrome gynécologique.","OKPS → SOPK. Comptez les lettres.","S-O-P-K = 4 lettres."]},
  {type:'C',e:'🔀',diff:'Difficile ★★★',dc:'diff3',title:'Le Cerveau Embrouillé',sub:'b↔d et m↔n — simulation dyslexie',ans:'1',
   confused:"um sur bix béveloppe um trouble b'appremtissage. le premier mombre em lettres bams ce texte est votre chiffre.",
   decoded:"<span class='ch'>UN</span> sur dix développe un trouble d'apprentissage. le premier nombre en lettres dans ce texte est votre chiffre.",
   hints:["Règle : 'b'='d', 'm'='n'. Cherchez le premier nombre en lettres dans le texte décodé.","Le mot 'um' dans le texte confus se décode en 'un' (m→n).","Le premier nombre en lettres est UN = 1."]},
  {type:'S',e:'🔣',diff:'Très difficile ★★★★',dc:'diff4',title:'La Chambre des Codes',sub:'Symboles + équation',ans:'6',
   eq:'🥄 × 💉 = ?',blur:'Le résultat est pair, entre 5 et 7.',q:"Résolvez l'équation avec les valeurs du tableau.",
   hints:["Dans le tableau : 🥄=3, 💉=2.","L'équation est une multiplication : 3 × 2 = ?","3 × 2 = 6."]}
]},
{id:6,name:'Série 6',code:'4928',rooms:[
  {type:'T',e:'📋',diff:'Facile ★',dc:'diff1',title:'La Salle des Pathologies',sub:'Tableau de correspondance',ans:'4',
   tbl:[{n:0,p:'Schizophrénie'},{n:1,p:'TOC'},{n:2,p:'Borderline'},{n:3,p:'Hyperlexie'},{n:4,p:'Prosopagnosie'},{n:5,p:'Misophonie'},{n:6,p:'Sensibilité sensorielle'},{n:7,p:'POTS'},{n:8,p:'Dysautonomie'},{n:9,p:'Dyspraxie'}],
   clues:["Je rends impossible la reconnaissance des visages — même ceux des proches. Ce n'est pas de la distraction, c'est entièrement neurologique.","Mon porteur doit utiliser d'autres indices : la voix, la coiffure, la démarche. Un visage familier peut lui sembler inconnu quelques heures après.","Je touche entre 2 et 2,5% de la population. Je suis totalement invisible de l'extérieur. Certaines célébrités l'ont révélée publiquement."],
   hints:["Cette pathologie empêche de reconnaître les visages. En grec 'prosopon'=visage.","Elle est surnommée 'cécité des visages'. Totalement invisible de l'extérieur.","Prosopagnosie est le numéro 4 dans le tableau."]},
  {type:'A',e:'🔤',diff:'Moyen ★★',dc:'diff2',title:'Le Laboratoire des Mots',sub:'Anagrammes de pathologies',ans:'9',
   words:[{s:'YIXDSPRAE',sol:'DYSPRAXIE',note:'Trouble de la coordination motrice'},{s:'SUPUL',sol:'LUPUS',note:'Maladie auto-immune'},{s:'COT',sol:'TOC',note:'Trouble obsessionnel compulsif'}],
   q:"Lequel désigne le trouble de la coordination motrice ? Comptez ses lettres.",
   hints:["YIXDSPRAE est l'anagramme du trouble de la coordination motrice.","YIXDSPRAE → DYSPRAXIE. Comptez les lettres.","D-Y-S-P-R-A-X-I-E = 9 lettres."]},
  {type:'C',e:'🔀',diff:'Difficile ★★★',dc:'diff3',title:'Le Cerveau Embrouillé',sub:'b↔d et m↔n — simulation dyslexie',ans:'2',
   confused:"beux pour cemt be la populatiom présemte ume forme be prosopagmosie. le premier mombre em lettres bams ce texte est votre chiffre.",
   decoded:"<span class='ch'>DEUX</span> pour cent de la population présente une forme de prosopagnosie. le premier nombre en lettres dans ce texte est votre chiffre.",
   hints:["Règle : 'b'='d', 'm'='n'. Cherchez le premier nombre en lettres dans le texte décodé.","Le mot 'beux' dans le texte confus se décode en 'deux' (b→d).","Le premier nombre en lettres est DEUX = 2."]},
  {type:'S',e:'🔣',diff:'Très difficile ★★★★',dc:'diff4',title:'La Chambre des Codes',sub:'Symboles + équation',ans:'8',
   eq:'🧠 + 💉 = ?',blur:'Le résultat est pair, entre 7 et 9.',q:"Résolvez l'équation avec les valeurs du tableau.",
   hints:["Dans le tableau : 🧠=6, 💉=2.","L'équation devient : 6 + 2 = ?","6 + 2 = 8."]}
]},
{id:7,name:'Série 7',code:'1673',rooms:[
  {type:'T',e:'📋',diff:'Facile ★',dc:'diff1',title:'La Salle des Pathologies',sub:'Tableau de correspondance',ans:'1',
   tbl:[{n:0,p:'Hémophilie'},{n:1,p:'VIH / SIDA'},{n:2,p:'Asthme sévère'},{n:3,p:'Narcolepsie'},{n:4,p:'Maladie de Crohn'},{n:5,p:'Trouble bipolaire'},{n:6,p:'Sclérose en plaques'},{n:7,p:'TSPT'},{n:8,p:'Mucoviscidose'},{n:9,p:'Drépanocytose'}],
   clues:["Grâce aux traitements modernes, mes porteurs vivent longtemps et quasi-normalement. Rien sur leur visage ne me trahit.","Mon porteur peut avoir une charge virale indétectable et ne plus être contagieux. Le secret médical me protège totalement.","Je touche 170 000 personnes en France. La stigmatisation reste forte. Je suis un handicap invisible reconnu par la MDPH."],
   hints:["Cette pathologie est traitée par des antirétroviraux. Son symbole est un ruban rouge.","3 lettres. Elle touche 170 000 personnes en France.","VIH / SIDA est le numéro 1 dans le tableau."]},
  {type:'A',e:'🔤',diff:'Moyen ★★',dc:'diff2',title:'Le Laboratoire des Mots',sub:'Anagrammes de pathologies',ans:'6',
   words:[{s:'HETSAM',sol:'ASTHME',note:'Maladie respiratoire chronique'},{s:'SUPUL',sol:'LUPUS',note:'Maladie auto-immune'},{s:'YIXDSPRAE',sol:'DYSPRAXIE',note:'Trouble de la coordination'}],
   q:"Lequel désigne la maladie respiratoire chronique ? Comptez ses lettres.",
   hints:["HETSAM est l'anagramme de la maladie respiratoire.","HETSAM → ASTHME. Comptez les lettres.","A-S-T-H-M-E = 6 lettres."]},
  {type:'C',e:'🔀',diff:'Difficile ★★★',dc:'diff3',title:'Le Cerveau Embrouillé',sub:'b↔d et m↔n — simulation dyslexie',ans:'7',
   confused:"sept pour cemt bes persommes souffremt b'asthme sévère. le premier mombre em lettres bams ce texte est votre chiffre.",
   decoded:"<span class='ch'>SEPT</span> pour cent des personnes souffrent d'asthme sévère. le premier nombre en lettres dans ce texte est votre chiffre.",
   hints:["Règle : 'b'='d', 'm'='n'. Cherchez le premier nombre en lettres dans le texte décodé.","SEPT ne contient ni b, ni d, ni m, ni n — il reste INCHANGÉ. C'est le piège !","Le premier nombre en lettres est SEPT = 7."]},
  {type:'S',e:'🔣',diff:'Très difficile ★★★★',dc:'diff4',title:'La Chambre des Codes',sub:'Symboles + équation',ans:'3',
   eq:'⚡ − 🧠 = ?',blur:'Le résultat est impair, entre 2 et 4.',q:"Résolvez l'équation avec les valeurs du tableau.",
   hints:["Dans le tableau : ⚡=9, 🧠=6.","L'équation devient : 9 − 6 = ?","9 − 6 = 3."]}
]},
{id:8,name:'Série 8',code:'8752',rooms:[
  {type:'T',e:'📋',diff:'Facile ★',dc:'diff1',title:'La Salle des Pathologies',sub:'Tableau de correspondance',ans:'8',
   tbl:[{n:0,p:'Migraine chronique'},{n:1,p:'Polyarthrite rhumatoïde'},{n:2,p:'Spondylarthrite'},{n:3,p:'Fibromyalgie'},{n:4,p:'Dépression'},{n:5,p:'SOPK'},{n:6,p:'Vaginisme'},{n:7,p:'Vulvodynie'},{n:8,p:'Eczéma chronique'},{n:9,p:'Vitiligo'}],
   clues:["Je ne suis pas qu'une peau sèche. Mes crises sont invalidantes : démangeaisons nocturnes intenses, peau qui saigne et suinte.","Je suis une maladie inflammatoire chronique. En rémission, je suis totalement invisible. Je reparais imprévisiblement selon les déclencheurs.","Le stress, les allergènes et la chaleur me déclenchent. Je touche 15% des enfants et 5% des adultes en France."],
   hints:["Cette pathologie est inflammatoire chronique de la peau. Son nom vient du grec 'bouillonner'.","Elle touche 15% des enfants. En rémission, invisible.","Eczéma chronique est le numéro 8 dans le tableau."]},
  {type:'A',e:'🔤',diff:'Moyen ★★',dc:'diff2',title:'Le Laboratoire des Mots',sub:'Anagrammes de pathologies',ans:'7',
   words:[{s:'TEBAIDE',sol:'DIABETE',note:"Maladie métabolique liée à l'insuline"},{s:'HETSAM',sol:'ASTHME',note:'Maladie respiratoire'},{s:'SUPUL',sol:'LUPUS',note:'Maladie auto-immune'}],
   q:"Lequel désigne la maladie métabolique liée à l'insuline ? Comptez ses lettres.",
   hints:["TEBAIDE est l'anagramme de la maladie métabolique.","TEBAIDE → DIABETE. Comptez les lettres.","D-I-A-B-E-T-E = 7 lettres."]},
  {type:'C',e:'🔀',diff:'Difficile ★★★',dc:'diff3',title:'Le Cerveau Embrouillé',sub:'b↔d et m↔n — simulation dyslexie',ans:'5',
   confused:"cimq pour cemt bes femmes souffremt be vagimisme. le premier mombre em lettres bams ce texte est votre chiffre.",
   decoded:"<span class='ch'>CINQ</span> pour cent des femmes souffrent de vaginisme. le premier nombre en lettres dans ce texte est votre chiffre.",
   hints:["Règle : 'b'='d', 'm'='n'. Cherchez le premier nombre en lettres dans le texte décodé.","Le mot 'cimq' dans le texte confus se décode en 'cinq' (m→n).","Le premier nombre en lettres est CINQ = 5."]},
  {type:'S',e:'🔣',diff:'Très difficile ★★★★',dc:'diff4',title:'La Chambre des Codes',sub:'Symboles + équation',ans:'2',
   eq:'🦋 − 🌸 = ?',blur:'Le résultat est pair, entre 1 et 3.',q:"Résolvez l'équation avec les valeurs du tableau.",
   hints:["Dans le tableau : 🦋=7, 🌸=5.","L'équation devient : 7 − 5 = ?","7 − 5 = 2."]}
]},
{id:9,name:'Série 9',code:'2589',rooms:[
  {type:'T',e:'📋',diff:'Facile ★',dc:'diff1',title:'La Salle des Pathologies',sub:'Tableau de correspondance',ans:'2',
   tbl:[{n:0,p:'Drépanocytose'},{n:1,p:'Mucoviscidose'},{n:2,p:'Lupus'},{n:3,p:'Narcolepsie'},{n:4,p:'Hémophilie'},{n:5,p:'POTS'},{n:6,p:'Dysautonomie'},{n:7,p:'Endométriose'},{n:8,p:'Sclérose en plaques'},{n:9,p:'Diabète type 1'}],
   clues:["Le papillon est mon emblème. Je touche principalement les femmes jeunes. Je suis une maladie auto-immune systémique.","Mon système immunitaire attaque mes propres organes — reins, cœur, poumons. De façon totalement imprévisible.","On m'appelle 'la grande simulatrice' car mes symptômes sont variés et difficiles à diagnostiquer. Je suis souvent longtemps méconnue."],
   hints:["Cette pathologie auto-immune a pour symbole le papillon.","Elle est surnommée 'la grande simulatrice'. Elle touche surtout les femmes.","Lupus est le numéro 2 dans le tableau."]},
  {type:'A',e:'🔤',diff:'Moyen ★★',dc:'diff2',title:'Le Laboratoire des Mots',sub:'Anagrammes de pathologies',ans:'5',
   words:[{s:'NHOCR',sol:'CROHN',note:"Maladie inflammatoire de l'intestin"},{s:'OKPS',sol:'SOPK',note:'Syndrome des ovaires polykystiques'},{s:'HETSAM',sol:'ASTHME',note:'Maladie respiratoire'}],
   q:"Lequel désigne la maladie inflammatoire de l'intestin ? Comptez ses lettres.",
   hints:["NHOCR est l'anagramme de la maladie inflammatoire intestinale.","NHOCR → CROHN. Comptez les lettres.","C-R-O-H-N = 5 lettres."]},
  {type:'C',e:'🔀',diff:'Difficile ★★★',dc:'diff3',title:'Le Cerveau Embrouillé',sub:'b↔d et m↔n — simulation dyslexie',ans:'8',
   confused:"huit pour cemt bes femmes souffremt b'embométriose. le premier mombre em lettres bams ce texte est votre chiffre.",
   decoded:"<span class='ch'>HUIT</span> pour cent des femmes souffrent d'endométriose. le premier nombre en lettres dans ce texte est votre chiffre.",
   hints:["Règle : 'b'='d', 'm'='n'. Cherchez le premier nombre en lettres dans le texte décodé.","HUIT ne contient ni b, ni d, ni m, ni n — il reste INCHANGÉ. C'est le piège !","Le premier nombre en lettres est HUIT = 8."]},
  {type:'S',e:'🔣',diff:'Très difficile ★★★★',dc:'diff4',title:'La Chambre des Codes',sub:'Symboles + équation',ans:'9',
   eq:'🦋 + 💉 = ?',blur:'Le résultat est impair, entre 8 et 10.',q:"Résolvez l'équation avec les valeurs du tableau.",
   hints:["Dans le tableau : 🦋=7, 💉=2.","L'équation devient : 7 + 2 = ?","7 + 2 = 9."]}
]},
{id:10,name:'Série 10',code:'5364',rooms:[
  {type:'T',e:'📋',diff:'Facile ★',dc:'diff1',title:'La Salle des Pathologies',sub:'Tableau de correspondance',ans:'5',
   tbl:[{n:0,p:'TSPT'},{n:1,p:'TDAH'},{n:2,p:'Hyperacousie'},{n:3,p:'Boulimie'},{n:4,p:'TOC'},{n:5,p:'Borderline'},{n:6,p:'Dyscalculie'},{n:7,p:'Dysorthographie'},{n:8,p:'Trouble bipolaire'},{n:9,p:'Schizophrénie'}],
   clues:["Je touche la régulation émotionnelle. Les émotions sont intenses, rapides, difficiles à contrôler — comme un thermostat émotionnel déréglé.","On me confond souvent avec la bipolarité. Mais mes oscillations durent des heures, pas des jours. Et mes relations aux autres sont très particulières.","Je touche 2% de la population. Je suis très stigmatisée mais très traitable avec la thérapie dialectique comportementale (TDC)."],
   hints:["Cette pathologie touche la régulation émotionnelle. Elle est traitée par la TDC.","Elle est souvent confondue avec la bipolarité mais les oscillations durent des heures.","Borderline est le numéro 5 dans le tableau."]},
  {type:'A',e:'🔤',diff:'Moyen ★★',dc:'diff2',title:'Le Laboratoire des Mots',sub:'Anagrammes de pathologies',ans:'3',
   words:[{s:'COT',sol:'TOC',note:'Trouble obsessionnel compulsif'},{s:'HETSAM',sol:'ASTHME',note:'Maladie respiratoire'},{s:'SUPUL',sol:'LUPUS',note:'Maladie auto-immune'}],
   q:"Lequel désigne le trouble obsessionnel compulsif ? Comptez ses lettres.",
   hints:["COT est l'anagramme du trouble obsessionnel compulsif.","COT → TOC. Comptez les lettres.","T-O-C = 3 lettres."]},
  {type:'C',e:'🔀',diff:'Difficile ★★★',dc:'diff3',title:'Le Cerveau Embrouillé',sub:'b↔d et m↔n — simulation dyslexie',ans:'6',
   confused:"six pour cemt be la populatiom présemte um toc à um momemt be sa vie. le premier mombre em lettres bams ce texte est votre chiffre.",
   decoded:"<span class='ch'>SIX</span> pour cent de la population présente un TOC à un moment de sa vie. le premier nombre en lettres dans ce texte est votre chiffre.",
   hints:["Règle : 'b'='d', 'm'='n'. Cherchez le premier nombre en lettres dans le texte décodé.","SIX ne contient ni b, ni d, ni m, ni n — il reste INCHANGÉ dans le texte confus.","Le premier nombre en lettres est SIX = 6."]},
  {type:'S',e:'🔣',diff:'Très difficile ★★★★',dc:'diff4',title:'La Chambre des Codes',sub:'Symboles + équation',ans:'4',
   eq:'🌸 − 💉 + 🌊 = ?',blur:'Le résultat est pair, entre 3 et 5.',q:"Résolvez l'équation avec les valeurs du tableau.",
   hints:["Dans le tableau : 🌸=5, 💉=2, 🌊=1.","L'équation devient : 5 − 2 + 1 = ?","5 − 2 + 1 = 4."]}
]}
];
