// ESCAPE GAME — DONNÉES BLOC B (Séries 11-20) — VERSION CORRIGÉE
const SERIES_B=[
{id:11,name:"Série 11",code:"2984",rooms:[
  {type:"T",e:"📋",diff:"Facile ★",dc:"diff1",title:"La Salle des Pathologies",sub:"Tableau de correspondance",ans:"2",
   tbl:[{n:0,p:"Fibromyalgie"},{n:1,p:"Dépression"},{n:2,p:"Narcolepsie"},{n:3,p:"TDAH"},{n:4,p:"Maladie de Crohn"},{n:5,p:"Hypersomnie"},{n:6,p:"Sclérose en plaques"},{n:7,p:"TSPT"},{n:8,p:"Trouble bipolaire"},{n:9,p:"Migraine chronique"}],
   clues:["Je suis un trouble neurologique du sommeil. Mon porteur peut s'endormir soudainement, en plein milieu d'une activité.","Mes attaques de sommeil sont incontrôlables et peuvent durer quelques secondes ou plusieurs minutes.","Je touche 1 personne sur 2000. Je suis souvent accompagnée de cataplexie."],
   hints:["Trouble neurologique du sommeil. Attaques soudaines incontrôlables.","Elle commence par N. Accompagnée de cataplexie.","Narcolepsie est le numéro 2 dans le tableau."]},
  {type:"A",e:"🔤",diff:"Moyen ★★",dc:"diff2",title:"Le Laboratoire des Mots",sub:"Anagrammes de pathologies",ans:"9",
   words:[{s:"EAIRLOPBI",sol:"BIPOLAIRE",note:"Trouble de l'humeur avec phases"},{s:"TEBAIDE",sol:"DIABETE",note:"Maladie métabolique"},{s:"HETSAM",sol:"ASTHME",note:"Maladie respiratoire"}],
   q:"Lequel désigne le trouble de l'humeur avec phases maniaques ? Comptez ses lettres.",
   hints:["EAIRLOPBI est l'anagramme du trouble de l'humeur.","EAIRLOPBI → BIPOLAIRE. Comptez les lettres.","B-I-P-O-L-A-I-R-E = 9 lettres."]},
  {type:"M",e:"🪞",diff:"Difficile ★★★",dc:"diff3",title:"Le Miroir Brisé",sub:"Texte en miroir — lisez chaque mot à l'envers",ans:"8",
   mirror_text:"ETCEFFA ENNOSREP 8 RUS 001 ERIALIPOB AL",
   real_decoded:"la bipolaire affecte <span class='ch'>8</span> personnes sur 100",
   q:"Quel chiffre apparaît dans la phrase une fois décodée ?",
   hints:["Lisez chaque mot à l'envers lettre par lettre.","ETCEFFA → AFFECTE, ENNOSREP → PERSONNE, 8 reste 8.","Le chiffre dans la phrase décodée est 8."]},
  {type:"MULTI",e:"🔢",diff:"Très difficile ★★★★",dc:"diff4",title:"La Multiplication Brisée",sub:"Trouvez le chiffre manquant",ans:"4",
   multi_display:"_ × _ = 16  →  16 ÷ 4 = ?",
   q:"Résolvez : trouvez combien font 16 divisé par 4.",
   hints:["16 ÷ 4 = ?","16 divisé par 4 égale 4.","Le chiffre est 4."]}
]},
{id:12,name:"Série 12",code:"5931",rooms:[
  {type:"T",e:"📋",diff:"Facile ★",dc:"diff1",title:"La Salle des Pathologies",sub:"Tableau de correspondance",ans:"5",
   tbl:[{n:0,p:"Dyscalculie"},{n:1,p:"Dysgraphie"},{n:2,p:"TOC"},{n:3,p:"Borderline"},{n:4,p:"TSPT"},{n:5,p:"Syndrome de Gilles de la Tourette"},{n:6,p:"Hyperlexie"},{n:7,p:"Prosopagnosie"},{n:8,p:"Misophonie"},{n:9,p:"Hyperacousie"}],
   clues:["Je suis un trouble neurologique avec des tics moteurs et vocaux involontaires et répétitifs.","Certains de mes porteurs émettent des sons ou des mots qu'ils ne peuvent pas contrôler.","Je touche environ 1% de la population mondiale, surtout les garçons."],
   hints:["Trouble neurologique avec tics moteurs et vocaux. Associé au TDAH.","Son nom complet est Syndrome de Gilles de la Tourette.","Le numéro 5 dans le tableau."]},
  {type:"A",e:"🔤",diff:"Moyen ★★",dc:"diff2",title:"Le Laboratoire des Mots",sub:"Anagrammes de pathologies",ans:"9",
   words:[{s:"YIXDSPRAE",sol:"DYSPRAXIE",note:"Trouble de la coordination motrice"},{s:"SUPUL",sol:"LUPUS",note:"Maladie auto-immune"},{s:"HETSAM",sol:"ASTHME",note:"Maladie respiratoire"}],
   q:"Lequel désigne le trouble de la coordination motrice ? Comptez ses lettres.",
   hints:["YIXDSPRAE est l'anagramme du trouble de la coordination.","YIXDSPRAE → DYSPRAXIE. Comptez les lettres.","D-Y-S-P-R-A-X-I-E = 9 lettres."]},
  {type:"M",e:"🪞",diff:"Difficile ★★★",dc:"diff3",title:"Le Miroir Brisé",sub:"Texte en miroir",ans:"3",
   mirror_text:"NOITALUPOP AL ED %3 SETCEFFA ETTEUROT ED EMORDNYS EL",
   real_decoded:"le syndrome de tourette affecte <span class='ch'>3</span>% de la population",
   q:"Quel chiffre apparaît dans la phrase une fois décodée ?",
   hints:["Lisez chaque mot à l'envers.","NOITALUPOP → POPULATION, %3 → 3%.","Le chiffre dans la phrase est 3."]},
  {type:"MULTI",e:"🔢",diff:"Très difficile ★★★★",dc:"diff4",title:"La Multiplication Brisée",sub:"Trouvez le chiffre manquant",ans:"1",
   multi_display:"_ × 9 = 9",
   q:"Trouvez le chiffre manquant : _ × 9 = 9.",
   hints:["_ × 9 = 9. Quel chiffre multiplié par 9 donne 9 ?","9 ÷ 9 = 1.","Le chiffre manquant est 1."]}
]},
{id:13,name:"Série 13",code:"7525",rooms:[
  {type:"T",e:"📋",diff:"Facile ★",dc:"diff1",title:"La Salle des Pathologies",sub:"Tableau de correspondance",ans:"7",
   tbl:[{n:0,p:"Fibromyalgie"},{n:1,p:"Dépression"},{n:2,p:"TDAH"},{n:3,p:"Endométriose"},{n:4,p:"Lupus"},{n:5,p:"Épilepsie"},{n:6,p:"Dyslexie"},{n:7,p:"SFC / Fatigue chronique"},{n:8,p:"Diabète type 1"},{n:9,p:"Maladie de Crohn"}],
   clues:["Mon porteur se réveille aussi fatigué qu'avant de dormir. La fatigue ne part jamais.","Je suis souvent déclenchée par une infection virale. Les examens classiques ne trouvent rien.","Mon acronyme signifie Syndrome de Fatigue Chronique. Je touche 2% de la population mondiale."],
   hints:["Fatigue permanente malgré le repos. Acronyme SFC.","Souvent déclenchée par une infection virale.","SFC / Fatigue chronique est le numéro 7 dans le tableau."]},
  {type:"A",e:"🔤",diff:"Moyen ★★",dc:"diff2",title:"Le Laboratoire des Mots",sub:"Anagrammes de pathologies",ans:"5",
   words:[{s:"HNOCR",sol:"CROHN",note:"Maladie inflammatoire intestinale"},{s:"SUPUL",sol:"LUPUS",note:"Maladie auto-immune"},{s:"COT",sol:"TOC",note:"Trouble obsessionnel"}],
   q:"Lequel désigne la maladie inflammatoire intestinale ? Comptez ses lettres.",
   hints:["HNOCR est l'anagramme de la maladie inflammatoire.","HNOCR → CROHN. Comptez les lettres.","C-R-O-H-N = 5 lettres."]},
  {type:"M",e:"🪞",diff:"Difficile ★★★",dc:"diff3",title:"Le Miroir Brisé",sub:"Texte en miroir",ans:"2",
   mirror_text:"SEMMEF SEL ED 2 RUS 1 ETCEFFA ESOIRTEMODNE L",
   real_decoded:"l endometriose affecte 1 sur <span class='ch'>2</span> femmes",
   q:"Quel est le dernier chiffre dans la phrase une fois décodée ?",
   hints:["Lisez chaque mot à l'envers.","SEMMEF → FEMMES, SEL → LES, 2 reste 2.","Le dernier chiffre dans la phrase est 2."]},
  {type:"MULTI",e:"🔢",diff:"Très difficile ★★★★",dc:"diff4",title:"La Multiplication Brisée",sub:"Trouvez le chiffre manquant",ans:"5",
   multi_display:"_ × 2 = 10",
   q:"Trouvez le chiffre manquant : _ × 2 = 10.",
   hints:["_ × 2 = 10. Divisez 10 par 2.","10 ÷ 2 = 5.","Le chiffre manquant est 5."]}
]},
{id:14,name:"Série 14",code:"3618",rooms:[
  {type:"T",e:"📋",diff:"Facile ★",dc:"diff1",title:"La Salle des Pathologies",sub:"Tableau de correspondance",ans:"3",
   tbl:[{n:0,p:"TSPT"},{n:1,p:"TOC"},{n:2,p:"Borderline"},{n:3,p:"Dyscalculie"},{n:4,p:"Dysgraphie"},{n:5,p:"Dysorthographie"},{n:6,p:"Sensibilité sensorielle"},{n:7,p:"Acouphènes"},{n:8,p:"POTS"},{n:9,p:"Dysautonomie"}],
   clues:["Je touche la manipulation des chiffres. Lire une horloge, rendre la monnaie sont des défis.","On me confond avec un manque de logique. Faux : je suis neurologique, pas intellectuelle.","Je suis le pendant mathématique de la dyslexie. Mon nom commence par DYS-."],
   hints:["Trouble neurologique lié aux maths. Pendant mathématique de la dyslexie.","Son nom commence par DYS-. Touche 3 à 6% de la population.","Dyscalculie est le numéro 3 dans le tableau."]},
  {type:"A",e:"🔤",diff:"Moyen ★★",dc:"diff2",title:"Le Laboratoire des Mots",sub:"Anagrammes de pathologies",ans:"6",
   words:[{s:"HETSAM",sol:"ASTHME",note:"Maladie respiratoire chronique"},{s:"SUPUL",sol:"LUPUS",note:"Maladie auto-immune"},{s:"TEBAIDE",sol:"DIABETE",note:"Maladie métabolique"}],
   q:"Lequel désigne la maladie respiratoire chronique ? Comptez ses lettres.",
   hints:["HETSAM est l'anagramme de la maladie respiratoire.","HETSAM → ASTHME. Comptez les lettres.","A-S-T-H-M-E = 6 lettres."]},
  {type:"M",e:"🪞",diff:"Difficile ★★★",dc:"diff3",title:"Le Miroir Brisé",sub:"Texte en miroir",ans:"1",
   mirror_text:"NOITALUPOP AL ED 1 RUS EUQILUCLASYCD AL ETCEFFA",
   real_decoded:"la dyscalculie affecte <span class='ch'>1</span> sur de la population",
   q:"Quel est le premier chiffre dans la phrase une fois décodée ?",
   hints:["Lisez chaque mot à l'envers.","NOITALUPOP → POPULATION, 1 reste 1.","Le premier chiffre dans la phrase est 1."]},
  {type:"MULTI",e:"🔢",diff:"Très difficile ★★★★",dc:"diff4",title:"La Multiplication Brisée",sub:"Trouvez le chiffre manquant",ans:"8",
   multi_display:"4 × _ = 32",
   q:"Trouvez le chiffre manquant : 4 × _ = 32.",
   hints:["4 × _ = 32. Divisez 32 par 4.","32 ÷ 4 = 8.","Le chiffre manquant est 8."]}
]},
{id:15,name:"Série 15",code:"9714",rooms:[
  {type:"T",e:"📋",diff:"Facile ★",dc:"diff1",title:"La Salle des Pathologies",sub:"Tableau de correspondance",ans:"9",
   tbl:[{n:0,p:"Hémophilie"},{n:1,p:"VIH/SIDA"},{n:2,p:"Drépanocytose"},{n:3,p:"Mucoviscidose"},{n:4,p:"Sclérose en plaques"},{n:5,p:"Polyarthrite rhumatoïde"},{n:6,p:"Spondylarthrite"},{n:7,p:"Maladie de Lyme chronique"},{n:8,p:"Vitiligo"},{n:9,p:"SOPK"}],
   clues:["Je suis un syndrome gynécologique chronique. Je touche 1 femme sur 10 en âge de procréer.","Mes symptômes incluent des cycles irréguliers et des kystes sur les ovaires.","Mon acronyme en français est SOPK. Je suis fortement sous-diagnostiquée."],
   hints:["Syndrome gynécologique. Acronyme SOPK. Touche 1 femme sur 10.","Cycles irréguliers, kystes sur les ovaires.","SOPK est le numéro 9 dans le tableau."]},
  {type:"A",e:"🔤",diff:"Moyen ★★",dc:"diff2",title:"Le Laboratoire des Mots",sub:"Anagrammes de pathologies",ans:"7",
   words:[{s:"TEBAIDE",sol:"DIABETE",note:"Maladie métabolique liée à l'insuline"},{s:"NHOCR",sol:"CROHN",note:"Maladie inflammatoire intestinale"},{s:"SUPUL",sol:"LUPUS",note:"Maladie auto-immune"}],
   q:"Lequel désigne la maladie liée à l'insuline ? Comptez ses lettres.",
   hints:["TEBAIDE est l'anagramme de la maladie liée à l'insuline.","TEBAIDE → DIABETE. Comptez les lettres.","D-I-A-B-E-T-E = 7 lettres."]},
  {type:"M",e:"🪞",diff:"Difficile ★★★",dc:"diff3",title:"Le Miroir Brisé",sub:"Texte en miroir",ans:"1",
   mirror_text:"SEMMEF XUD 1 RUS ETCEFFA KSPOS EL",
   real_decoded:"le SOPK affecte <span class='ch'>1</span> sur dix femmes",
   q:"Quel est le premier chiffre dans la phrase une fois décodée ?",
   hints:["Lisez chaque mot à l'envers.","SEMMEF → FEMMES, 1 reste 1.","Le premier chiffre dans la phrase est 1."]},
  {type:"MULTI",e:"🔢",diff:"Très difficile ★★★★",dc:"diff4",title:"La Multiplication Brisée",sub:"Trouvez le chiffre manquant",ans:"4",
   multi_display:"_ × 5 = 20",
   q:"Trouvez le chiffre manquant : _ × 5 = 20.",
   hints:["_ × 5 = 20. Divisez 20 par 5.","20 ÷ 5 = 4.","Le chiffre manquant est 4."]}
]},
{id:16,name:"Série 16",code:"4729",rooms:[
  {type:"T",e:"📋",diff:"Facile ★",dc:"diff1",title:"La Salle des Pathologies",sub:"Tableau de correspondance",ans:"4",
   tbl:[{n:0,p:"Schizophrénie"},{n:1,p:"TSPT"},{n:2,p:"TOC"},{n:3,p:"Trouble bipolaire"},{n:4,p:"Trouble panique"},{n:5,p:"Phobie sociale"},{n:6,p:"Agoraphobie"},{n:7,p:"Hypocondrie"},{n:8,p:"Anorexie mentale"},{n:9,p:"Boulimie"}],
   clues:["Je suis caractérisé par des épisodes soudains de peur intense, avec palpitations et sueurs.","Je suis souvent confondu avec une urgence cardiaque. Aux urgences, tout revient normal.","Je touche 3 à 5% de la population. Je suis très traitable par thérapie cognitive."],
   hints:["Épisodes soudains de peur intense. Souvent confondu avec un malaise cardiaque.","Traitable par TCC. Peut mener à l'agoraphobie.","Trouble panique est le numéro 4 dans le tableau."]},
  {type:"A",e:"🔤",diff:"Moyen ★★",dc:"diff2",title:"Le Laboratoire des Mots",sub:"Anagrammes de pathologies",ans:"7",
   words:[{s:"TEBAIDE",sol:"DIABETE",note:"Maladie métabolique liée au sucre"},{s:"COT",sol:"TOC",note:"Trouble obsessionnel"},{s:"SUPUL",sol:"LUPUS",note:"Maladie auto-immune"}],
   q:"Lequel désigne la maladie métabolique liée au sucre ? Comptez ses lettres.",
   hints:["TEBAIDE est l'anagramme de la maladie liée au sucre.","TEBAIDE → DIABETE. Comptez les lettres.","D-I-A-B-E-T-E = 7 lettres."]},
  {type:"M",e:"🪞",diff:"Difficile ★★★",dc:"diff3",title:"Le Miroir Brisé",sub:"Texte en miroir",ans:"2",
   mirror_text:"NOITALUPOP AL ED 2 RUS 1 EUQINAP ELBUORT EL ETCEFFA",
   real_decoded:"le trouble panique affecte <span class='ch'>1</span> sur <span class='ch'>2</span> de la population",
   q:"Quel est le deuxième chiffre dans la phrase une fois décodée ?",
   hints:["Lisez chaque mot à l'envers.","1 et 2 apparaissent dans la phrase décodée.","Le deuxième chiffre dans la phrase est 2."]},
  {type:"MULTI",e:"🔢",diff:"Très difficile ★★★★",dc:"diff4",title:"La Multiplication Brisée",sub:"Trouvez le chiffre manquant",ans:"9",
   multi_display:"_ × 3 = 27",
   q:"Trouvez le chiffre manquant : _ × 3 = 27.",
   hints:["_ × 3 = 27. Divisez 27 par 3.","27 ÷ 3 = 9.","Le chiffre manquant est 9."]}
]},
{id:17,name:"Série 17",code:"6458",rooms:[
  {type:"T",e:"📋",diff:"Facile ★",dc:"diff1",title:"La Salle des Pathologies",sub:"Tableau de correspondance",ans:"6",
   tbl:[{n:0,p:"Vitiligo"},{n:1,p:"Eczéma chronique"},{n:2,p:"Psoriasis"},{n:3,p:"Rosacea"},{n:4,p:"Ichtyose"},{n:5,p:"Maladie de Raynaud"},{n:6,p:"Syndrome des jambes sans repos"},{n:7,p:"Hypersomnie idiopathique"},{n:8,p:"Apnée du sommeil"},{n:9,p:"Insomnie chronique"}],
   clues:["Dès que je m'allonge, une sensation irrésistible de bouger les jambes apparaît. Fourmillements, picotements.","Mon porteur ne peut pas s'empêcher de bouger, surtout le soir. Le sommeil devient impossible.","Je touche 5 à 10% des adultes. Je suis une pathologie neurologique reconnue."],
   hints:["Pathologie neurologique : envie irrésistible de bouger les jambes au repos.","Touche 5-10% des adultes. Perturbe gravement le sommeil.","Syndrome des jambes sans repos est le numéro 6 dans le tableau."]},
  {type:"A",e:"🔤",diff:"Moyen ★★",dc:"diff2",title:"Le Laboratoire des Mots",sub:"Anagrammes de pathologies",ans:"4",
   words:[{s:"OKPS",sol:"SOPK",note:"Syndrome gynécologique"},{s:"TEBAIDE",sol:"DIABETE",note:"Maladie métabolique"},{s:"COT",sol:"TOC",note:"Trouble obsessionnel"}],
   q:"Lequel désigne le syndrome gynécologique lié aux ovaires ? Comptez ses lettres.",
   hints:["OKPS est l'anagramme du syndrome gynécologique.","OKPS → SOPK. Comptez les lettres.","S-O-P-K = 4 lettres."]},
  {type:"M",e:"🪞",diff:"Difficile ★★★",dc:"diff3",title:"Le Miroir Brisé",sub:"Texte en miroir",ans:"5",
   mirror_text:"ELARENEG NOITALUPOP AL ED %5 ETCEFFA SOPERS SNAS SBMAJ SED EMORDNYS EL",
   real_decoded:"le syndrome des jambes sans repos affecte <span class='ch'>5</span>% de la population generale",
   q:"Quel est le chiffre dans la phrase une fois décodée ?",
   hints:["Lisez chaque mot à l'envers pour décoder la phrase.","ELARENEG → GENERALE, %5 → 5%.","Le chiffre dans la phrase est 5."]},
  {type:"MULTI",e:"🔢",diff:"Très difficile ★★★★",dc:"diff4",title:"La Multiplication Brisée",sub:"Trouvez le chiffre manquant",ans:"8",
   multi_display:"4 × _ = 32",
   q:"Trouvez le chiffre manquant : 4 × _ = 32.",
   hints:["4 × _ = 32. Divisez 32 par 4.","32 ÷ 4 = 8.","Le chiffre manquant est 8."]}
]},
{id:18,name:"Série 18",code:"1563",rooms:[
  {type:"T",e:"📋",diff:"Facile ★",dc:"diff1",title:"La Salle des Pathologies",sub:"Tableau de correspondance",ans:"1",
   tbl:[{n:0,p:"Hyperacousie"},{n:1,p:"Misophonie"},{n:2,p:"Phonophobie"},{n:3,p:"Acouphènes"},{n:4,p:"Surdité partielle"},{n:5,p:"Dyslexie visuelle"},{n:6,p:"Scotome scintillant"},{n:7,p:"Photophobie"},{n:8,p:"Dyschromatopsie"},{n:9,p:"Cécité des couleurs"}],
   clues:["Certains sons déclenchent une réaction émotionnelle intense : rage, anxiété. Le bruit de mastication est insupportable.","Je cible des sons spécifiques produits par d'autres personnes. Ce n'est pas de l'hyperacousie.","Je suis différente de l'hyperacousie. Moi, je suis émotionnellement déclenchée par des sons précis."],
   hints:["Réaction émotionnelle intense à des sons spécifiques.","Différente de l'hyperacousie. Déclenche rage ou dégoût.","Misophonie est le numéro 1 dans le tableau."]},
  {type:"A",e:"🔤",diff:"Moyen ★★",dc:"diff2",title:"Le Laboratoire des Mots",sub:"Anagrammes de pathologies",ans:"5",
   words:[{s:"HNOCR",sol:"CROHN",note:"Maladie inflammatoire intestinale"},{s:"OKPS",sol:"SOPK",note:"Syndrome gynécologique"},{s:"HETSAM",sol:"ASTHME",note:"Maladie respiratoire"}],
   q:"Lequel désigne la maladie inflammatoire intestinale ? Comptez ses lettres.",
   hints:["HNOCR est l'anagramme de la maladie inflammatoire.","HNOCR → CROHN. Comptez les lettres.","C-R-O-H-N = 5 lettres."]},
  {type:"M",e:"🪞",diff:"Difficile ★★★",dc:"diff3",title:"Le Miroir Brisé",sub:"Texte en miroir",ans:"6",
   mirror_text:"ENNOSREP 6 RUS 1 ETCEFFA EINOHPOSIM AL",
   real_decoded:"la misophonie affecte <span class='ch'>1</span> sur <span class='ch'>6</span> personne",
   q:"Quel est le deuxième chiffre dans la phrase une fois décodée ?",
   hints:["Lisez chaque mot à l'envers.","1 et 6 apparaissent dans la phrase décodée.","Le deuxième chiffre est 6."]},
  {type:"MULTI",e:"🔢",diff:"Très difficile ★★★★",dc:"diff4",title:"La Multiplication Brisée",sub:"Trouvez le chiffre manquant",ans:"3",
   multi_display:"_ × 7 = 21",
   q:"Trouvez le chiffre manquant : _ × 7 = 21.",
   hints:["_ × 7 = 21. Divisez 21 par 7.","21 ÷ 7 = 3.","Le chiffre manquant est 3."]}
]},
{id:19,name:"Série 19",code:"8636",rooms:[
  {type:"T",e:"📋",diff:"Facile ★",dc:"diff1",title:"La Salle des Pathologies",sub:"Tableau de correspondance",ans:"8",
   tbl:[{n:0,p:"Fibromyalgie"},{n:1,p:"Endométriose"},{n:2,p:"TDAH"},{n:3,p:"Narcolepsie"},{n:4,p:"Dyspraxie"},{n:5,p:"Dyscalculie"},{n:6,p:"Dyslexie"},{n:7,p:"Dysgraphie"},{n:8,p:"Dysorthographie"},{n:9,p:"Hyperlexie"}],
   clues:["Je touche l'écrit. Mon porteur peut lire correctement mais produit des fautes persistantes.","Je ne suis pas liée au niveau intellectuel. Je reflète une difficulté à encoder les règles orthographiques.","Je suis distincte de la dyslexie. Mon nom commence par DYS-."],
   hints:["Trouble de l'orthographe distincte de la dyslexie. Commence par DYS-.","On peut bien lire mais mal orthographier.","Dysorthographie est le numéro 8 dans le tableau."]},
  {type:"A",e:"🔤",diff:"Moyen ★★",dc:"diff2",title:"Le Laboratoire des Mots",sub:"Anagrammes de pathologies",ans:"6",
   words:[{s:"HETSAM",sol:"ASTHME",note:"Maladie respiratoire chronique"},{s:"TEBAIDE",sol:"DIABETE",note:"Maladie métabolique"},{s:"NHOCR",sol:"CROHN",note:"Maladie inflammatoire"}],
   q:"Lequel désigne la maladie respiratoire chronique ? Comptez ses lettres.",
   hints:["HETSAM est l'anagramme de la maladie respiratoire.","HETSAM → ASTHME. Comptez les lettres.","A-S-T-H-M-E = 6 lettres."]},
  {type:"M",e:"🪞",diff:"Difficile ★★★",dc:"diff3",title:"Le Miroir Brisé",sub:"Texte en miroir",ans:"3",
   mirror_text:"SEPYT 3 A EIBARGOHTORYSID AL",
   real_decoded:"la dysorthographie a <span class='ch'>3</span> types",
   q:"Quel est le chiffre dans la phrase une fois décodée ?",
   hints:["Lisez chaque mot à l'envers.","SEPYT → TYPES, 3 reste 3.","Le chiffre dans la phrase est 3."]},
  {type:"MULTI",e:"🔢",diff:"Très difficile ★★★★",dc:"diff4",title:"La Multiplication Brisée",sub:"Trouvez le chiffre manquant",ans:"6",
   multi_display:"_ × 6 = 36",
   q:"Trouvez le chiffre manquant : _ × 6 = 36.",
   hints:["_ × 6 = 36. Divisez 36 par 6.","36 ÷ 6 = 6.","Le chiffre manquant est 6."]}
]},
{id:20,name:"Série 20",code:"7514",rooms:[
  {type:"T",e:"📋",diff:"Facile ★",dc:"diff1",title:"La Salle des Pathologies",sub:"Tableau de correspondance",ans:"7",
   tbl:[{n:0,p:"Vaginisme"},{n:1,p:"Vulvodynie"},{n:2,p:"Endométriose"},{n:3,p:"Adénomyose"},{n:4,p:"SOPK"},{n:5,p:"SPM sévère"},{n:6,p:"Fibromyalgie pelvienne"},{n:7,p:"Cystite interstitielle"},{n:8,p:"Vestibulodynie"},{n:9,p:"Dyspareunie chronique"}],
   clues:["Je touche la vessie mais je ne suis pas une infection. Mon porteur ressent une douleur permanente.","Mes symptômes ressemblent à une cystite mais sans bactérie. Les antibiotiques ne fonctionnent pas.","Je touche 1 à 4% des femmes et reste très sous-diagnostiquée."],
   hints:["Douleur vésicale chronique sans infection. Ressemble à une cystite sans bactéries.","Résiste aux antibiotiques. Touche 1-4% des femmes.","Cystite interstitielle est le numéro 7 dans le tableau."]},
  {type:"A",e:"🔤",diff:"Moyen ★★",dc:"diff2",title:"Le Laboratoire des Mots",sub:"Anagrammes de pathologies",ans:"5",
   words:[{s:"HNOCR",sol:"CROHN",note:"Maladie inflammatoire intestinale"},{s:"SUPUL",sol:"LUPUS",note:"Maladie auto-immune"},{s:"OKPS",sol:"SOPK",note:"Syndrome gynécologique"}],
   q:"Lequel désigne la maladie inflammatoire intestinale ? Comptez ses lettres.",
   hints:["HNOCR est l'anagramme de la maladie inflammatoire.","HNOCR → CROHN. Comptez les lettres.","C-R-O-H-N = 5 lettres."]},
  {type:"M",e:"🪞",diff:"Difficile ★★★",dc:"diff3",title:"Le Miroir Brisé",sub:"Texte en miroir",ans:"1",
   mirror_text:"ENNOSREP 1 RUS ETCEFFA ELLEITSITRETNI ETITSYC AL",
   real_decoded:"la cystite interstitielle affecte <span class='ch'>1</span> sur personne",
   q:"Quel est le premier chiffre dans la phrase une fois décodée ?",
   hints:["Lisez chaque mot à l'envers.","1 apparaît dans la phrase décodée.","Le premier chiffre est 1."]},
  {type:"MULTI",e:"🔢",diff:"Très difficile ★★★★",dc:"diff4",title:"La Multiplication Brisée",sub:"Double opération",ans:"4",
   multi_display:"_ × 4 = 16  puis  16 ÷ 4 = ?",
   q:"Résolvez les 2 étapes. Le résultat final est votre chiffre.",
   hints:["_ × 4 = 16 donc _ = 4. Puis 16 ÷ 4 = ?","16 ÷ 4 = 4.","Le chiffre final est 4."]}
]}
];